version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports: 
      - 80:80
    container_name: avia-back_nginx
    depends_on:
      - app
      
  app:
    build: 
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    container_name: avia-back_app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "avia-db"
      POSTGRES_USER: "avia-user"
      POSTGRES_PASSWORD: BYiaGewrEFLgnij
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    container_name: avia-front_db
