name: Deploy backend
on:
  push:
    branches:
      - main
  workflow_dispatch:    
      
jobs:
  prepare-environment:
    runs-on: self-hosted
    steps:
      - name: Stop and remove containers, networks
        run: docker-compose down
      - name: Remove unused data
        run: docker system prune -a -f

  deploy:
    needs: prepare-environment
    runs-on: self-hosted
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: docker-compose
        run: docker-compose up -d
      - name: install composer
        run: docker exec -d avia-back_app composer install     
      - name: storage
        run: docker exec -d avia-back_app chmod 777 -R storage       
      - name: migrate
        run: docker exec -d avia-back_app php artisan migrate:refresh --seed       
      - name: swagger
        run: docker exec -d avia-back_app php artisan L5-swagger:generate  

   
